spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruit-shop
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true